# Site configuration

##################
# Basic Variable #
##################

#; site.title = "Wenger"

########################
# Global Configuration #
########################

# Change the directory where Jekyll will read files.
#; source: .
# Change the directory where Jekyll will write files.
#; destination: ./books
# Disable non-whitelisted plugins, caching to disk, and ignore symbolic links.
#; safe: false
# Disable caching of content to disk in order to skip creating a .jekyll-cache 
# or similar directory at the source to avoid interference with virtual 
# environments and third-party directory watchers. Caching to disk is always 
# disabled in safe mode.
# Note:
# @support version: 4.1.0+
#; disable_disk_cache: false
# Jekyll 4.0 started allowing themes to bundle a _config.yml to simplify 
# theme-onboarding for new users. In the unfortunate situation that importing 
# a bundled theme configuration messes up the merged site-configuration, the 
# user can configure Jekyll to not import the theme-config entirely.
# Note:
# @support version: 4.1.0+
#; ignore_theme_config: false
# Exclude directories and/or files from the conversion. These exclusions are 
# relative to the site's source directory and cannot be outside the source 
# directory.
#: exclude:
# Force inclusion of directories and/or files in the conversion. .htaccess is a 
# good example since dotfiles are excluded by default.
#; inlcude:
# When clobbering the site destination, keep the selected files. Useful for 
# files that are not generated by jekyll; e.g. files or assets that are 
# generated by your build tool. The paths are relative to the destination
#; keep_file: 
# Set the time zone for site generation. This sets the TZ environment variable, 
# which Ruby uses to handle time and date creation and manipulation. Any entry 
# from the IANA Time Zone Database is valid, e.g. America/New_York. A list of 
# all available values can be found here. When serving on a local machine, the 
# default time zone is set by your operating system. But when served on a 
# remote host/server, the default time zone depends on the server's setting or 
# location.
#; timezone: null
# Set the encoding of files by name (only available for Ruby 1.9 or later). The 
# default value is utf-8 starting in 2.0.0, and nil before 2.0.0, which will 
# yield the Ruby default of ASCII-8BIT. Available encodings can be shown by the 
# command `ruby -e 'puts Encoding::list.join("\n")'`.
#; encoding:

# Front Matter Defaults
# <https://jekyllrb.com/docs/configuration/front-matter-defaults/>

#; default:
#;   - scope:
      # an empty string here means all files in the project
#;       path: ""
#;    values:
#;      layout: "default"


#########################
# Build Command Options #
#########################

# Specify plugin directories instead of using _plugins/ automatically.
#; plugins_dir:
# Specify layout directory instead of using _layouts/ automatically.
#; layouts_dir:
# Process and render draft posts.
#; show_drafts: 
# Publish posts or collection documents with a future date.
#; future:
# Render posts that were marked as unpublished.
#; unpublished:
# Produce an index for related posts. Requires the classifier-reborn plugin.
#; lsi: 
# Serve the website from the given base URL.
#; baseurl: 

#########################
# Serve Command Options #
#########################

# Listen on the given port. The default is `4000`.
#; port: 4000
# Listen at the given hostname. The default is `localhost`.
#; host: 


##########
# Themes #
##########

#; theme: minima
remote_theme: sighingnow/jekyll-gitbook

####################
# Markdown Options #
####################

# <https://jekyllrb.com/docs/configuration/markdown/>

# Kramdown is the default Markdown renderer for Jekyll, and often works well 
# with no additional configuration. However, it does support many configuration 
# options.

# By default, Jekyll uses the GitHub Flavored Markdown (GFM) processor for 
# Kramdown.

#; kramdown:
#;   header_offset: 2
  # To use the CodeRay syntax highlighter with Kramdown, you need to add a 
  # dependency on the kramdown-syntax-coderay gem.
#;   syntax_highlighter: coderay  


##################
# Liquid Options #
##################

#; liquid:
#;   error_mode: strict

###################
# WEBrick Options #
###################

# You can provide custom headers for your site by adding them to _config.yml.

#; webrick:
#;   headers:

##################
# Jekyll Plugins #
##################

plugins:
  # plugin will auto create index.html from README.md.
  - jekyll-readme-index
  - jekyll-feed
  - jekyll-seo-tag 
#:  - kramdown-syntax-coderay
