title: GitHub Page for Wenger Binning
lang
url: "https://wengerbinning.github.io"

author: Wenger Binning
email: wengerbinning@163.com
github_username: Wenger Binning
twitter_username: Wenger Binning

encoding: UTF-8
markdown: kramdown

# 
# themes
#

theme: jekyll-theme-minimal

# gitbook themes
# remote_theme: sighingnow/jekyll-gitbook
# remote_theme: rundocs/jekyll-rtd-theme

plugins:
  - jekyll-coffeescript
  # convert relative links to Markdown files to their rendered equivalents.
  - jekyll-relative-links
  - jekyll-paginate
  - jekyll-github-metadata
  - jekyll-avatar
  - jekyll-mentions
  - jemoji

permalink: /:year/:title:output_ext