#
# Websites Basic Setting
#
title: 
  cn-name: 文彬的开发手册
  en-name: Wenger handbook

# 
timezone: Asia/Shanghai

author:
  cn-name: 郑文彬
  en-name: Wenger Binning
  email:
    - Netease: wengerbinning@163.com
    - Gmail: wengerbinning@gmail.com

#
source: ./
destination: ./_site
layouts: ./_layouts
data_source: ./_data
plugins_dir: ./_plugins

