#
# Website Basic Setting
#

site.title = "Wenger"


#
# Website Theme 
#

theme: minima

#
# Website Plugins
#

plugins:
  - jekyll-seo-tag
  # plugin will auto create index.html from README.md.
  - jekyll-readme-index
