
### BASSIC ###

# Disable non-whitelisted plugins, caching to disk, and ignore symbolic links.
safe: true


### PLUGINS ###

plugins:
- jekyll-remote-theme


### COMMON ###

# Produce an index for related posts. Requires the classifier-reborn plugin.
lsi: false
# Enable the experimental incremental build feature.
incremental: false


### THEMES ###

remote_theme: pages-themes/architect@v0.2.0

title: WENGER BINNING
description: This is a handbook about all.


### OTHERS ###

gist:
  noscript: false

kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge