title: Wenger GitHub Page
email: wengerbinning@163.com
url: "https://wengerbinning.github.io"
markdown: kramdown

encoding: UTF-8

# 
# themes
#

# gitbook themes
# remote_theme: sighingnow/jekyll-gitbook
# remote_theme: rundocs/jekyll-rtd-theme

plugins:
  - jekyll-coffeescript
  # convert relative links to Markdown files to their rendered equivalents.
  - jekyll-relative-links
  - jekyll-paginate
  - jekyll-github-metadata

permalink: /:year/:title:output_ext