#
# Websites Basic Setting
#

title: Wenger Binning GitHub Page

# 
timezone: Asia/Shanghai

author:
  cn-name: 郑文彬
  en-name: Wenger Binning
  email:
    - Netease: wengerbinning@163.com
    - Gmail: wengerbinning@gmail.com


theme: minima

#
# YMAL header information
#


#
# plugins
#

plugins:
  - jekyll-seo-tag
  # plugin will auto create index.html from README.md.
  - jekyll-readme-index
