// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import { frontmatter as fm0, toc as t0 } from '/vcs/wenger/wengerbinning.github.io/docs/guide.md?type=frontmatter';
import { demoIndex as dmi0 } from '/vcs/wenger/wengerbinning.github.io/docs/guide.md?type=demo-index';
import { frontmatter as fm1, toc as t1 } from '/vcs/wenger/wengerbinning.github.io/docs/index.md?type=frontmatter';
import { demoIndex as dmi1 } from '/vcs/wenger/wengerbinning.github.io/docs/index.md?type=demo-index';

export const filesMeta = {
  'docs/guide': {
    frontmatter: fm0,
    toc: t0,
    demoIndex: dmi0,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/vcs/wenger/wengerbinning.github.io/docs/guide.md?type=text'),
  },
  'docs/index': {
    frontmatter: fm1,
    toc: t1,
    demoIndex: dmi1,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/vcs/wenger/wengerbinning.github.io/docs/index.md?type=text'),
  },
}

export { tabs as tabsMeta } from './tabs';
