// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/vcs/wenger/wengerbinning.github.io/node_modules/dumi/theme-default/builtins/CodeGroup/index.js';
